behaviors:
  roller-ball-01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
  roller-ball-optimized-01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 1.0e-3
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.2
      curiosity:
        gamma: 0.99
        strength: 0.01
        encoding_size: 256
        learning_rate: 1.0e-3
    max_steps: 1000000
    time_horizon: 1024
    summary_freq: 5000
env_settings:
  env_path: env-builds/TutorialRollerBallOptimizedEnv-build-v0.1.0/TutorialRollerBallOptimizedEnv.exe # Windows
  num_envs: 32
  seed: 20241007 # Environment-level seed
engine_settings:
  no_graphics: false
checkpoint_settings:
  run_id: roller-ball-01-2024-10-07
  force: true
